name: Basic Scan Example
                                                                                                                                                                                                                                         
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
                                                                                                                                                                                                                                         
jobs:
  polaris-scan:
    runs-on: [mac-arm-sh]
                                                                                                                                                                                                                                         
    steps:
    
    - name: Checkout Source
      uses: actions/checkout@v4
                                                                                                                                                                                                                                         
    - name: Polaris Scan
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        polaris_assessment_types: "SCA,SAST"
        detect_args: "--detect.source.path=${{ github.workspace }}/nodejs-npm"
